app = "roseate-wms"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_URL = "sqlite:////app/instance/wms.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "roseate_storage"
  destination = "/app/instance"
